### ISSUE TITLE
Add products

### ISSUE THREAD

**Issue by clri** [clri/first-microservices#5]
Redesign product DAO/Relational table as defined in meeting with prof (id, name, description, image URL--maybe some other details as well). Add BO layer/business logic, frontend to display, unit tests

**Comment by arjunm12** [comment]
Made product changes in customers.sql but need to make changes to Amazon database. Also, need to finish "Add BO layer/business logic, frontend to display, unit tests".

**Comment by clri** [comment]
BO/DO added

**Comment by clri** [comment]
frontend added
